;PROGRAM TO MULTIPLY THREE NUMBERS AND PRINT THE RESULT

dosseg
.model small
.stack 100h
.data

.code

main proc

    mov al, 6   ;  THIS IS THE FIRST NUMBER WHICH IS IN THE AL REGISTER 
    mov bl, 2   ;  THIS IS THE SECOND NUMBER WHICH IS IN THE BL REGISTER 
    mov dh, 4   ;  THIS IS THE THIRD NUMBER WHICH IS IN THE DH REGISTER
    mul bl
    mul dh
    AAM          ; THIS AAM METHOD USE TO STORE THE RESULT VALUE WHICH IS STORED IN THE SPLITED REGISTER TO SAVE THE VALUE  

    mov ch, ah   ;  THE CH REGISTER STORES THE VALUE STORED IN AH REGISTER.
    mov cl, al   ;  THE CL REGISTER STORES THE VALUE STORED IN AL REGISTER

    mov dl, ch
    add dl, 48
    mov ah, 2
    int 21h

    mov dl, cl
    add dl, 48
    mov ah, 2
    int 21h

    mov ah, 4ch
    int 21h

main endp
end main
; HERE THE FUNCTION OF AAM(ASCII ADJUST AFTER MULTIPLICATION) ITS PURPOSE IS TO SPLIT THE RESULT IN TWO REGISTER(AX: AH, AL) AND THEN DISPLAY THE RESULT.
; THIS AAM IS BENEFICAL WHEN THE RESULT OF MULTIPLICATION IS OF TWO DIGITS(e.g 10, 55, 60 etc) SO THIS AAM SPLIT THE REGISTER INTO THE UPPER PART AND IN THE LOWER PART
; FOR EXAMPLE: WE ARE MULTIPLYING TWO NUMBERS AND ITS RESULT IS 15. SO THE AAM SPLIT THE REGISTER AX INTO UPPER AND LOWER PART AND STORE IT(AX = AH: 1, AL: 5) AND THEN DISPLAY THE RESULT.  