; PROGRAM USING LOOP AND PRINT THE NUMBERS 1 TO 10

dosseg
.model small
.stack 100h
.data
.code
main proc

  mov cx, 10    ; IT INDICATE THAT THE LOOP WILL EXECUTE HOW MANY TIME 
  mov dx, 49    ; THIS IS THE ASSCI CODE OF THE NO: ONE(1) WHICH IS 49 FROM WHERE THE LOOP STARTS

  Loopings:     ; THIS THE LABEL NAME
  mov ah, 2     ; HERE THE PRINT THE VALUES USING LOOP
  int 21h       ; THEN THIS COMMAND STOPS ALL THE FUNCTION IN THE PROGRAM 
  inc dx        ; THIS COMMAND INCREASE ONE NUMBER WHEN THE LOOP CALL AGAIN

  loop Loopings ; AND FINALLY HERE IS THE LOOP AND THE LABEL NAME WHICH HELPS TO CALL IT AGAIN WHERE THERE IS A NEED TO CALL

  mov ah, 4ch
  int 21h
main endp
end main