;PROGRAM TO SUBTRACT TWO NUMBERS AND PRINT THE RESULT

dosseg
.model small
.stack 100h
.data
.code
main proc

mov al, 12   ; THIS IS THE FIRST NUMBER 
mov bl, 5    ; THIS IS THE SECOND NUMBER 
sub al, bl   ; HERE WE SUBTRACT THE SECOND NUMBER FROM THE FIRST NUMBER
add al, 48   ; THEN WE ADD THE ASSCI CODE OF ZERO(0) WHICH IS 48 TO GET THE PERFECT RESULT WHICH WE WANT
mov dl, al
mov ah, 2    ; THEN FINALLY WE PRINT THE RESULT
int 21h      ; THIS COMMAND IS USED TO STOP ALL THE WORKING DOING IN THE PROGRAM.

mov ah, 4ch
int 21h
main endp
end main